# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Coordination.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Coordination.proto',
  package='exec',
  serialized_pb=_b('\n\x12\x43oordination.proto\x12\x04\x65xec\"{\n\x10\x44rillbitEndpoint\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x11\n\tuser_port\x18\x02 \x01(\x05\x12\x14\n\x0c\x63ontrol_port\x18\x03 \x01(\x05\x12\x11\n\tdata_port\x18\x04 \x01(\x05\x12\x1a\n\x05roles\x18\x05 \x01(\x0b\x32\x0b.exec.Roles\"i\n\x14\x44rillServiceInstance\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1b\n\x13registrationTimeUTC\x18\x02 \x01(\x03\x12(\n\x08\x65ndpoint\x18\x03 \x01(\x0b\x32\x16.exec.DrillbitEndpoint\"\x97\x01\n\x05Roles\x12\x17\n\tsql_query\x18\x01 \x01(\x08:\x04true\x12\x1a\n\x0clogical_plan\x18\x02 \x01(\x08:\x04true\x12\x1b\n\rphysical_plan\x18\x03 \x01(\x08:\x04true\x12\x1b\n\rjava_executor\x18\x04 \x01(\x08:\x04true\x12\x1f\n\x11\x64istributed_cache\x18\x05 \x01(\x08:\x04trueB3\n\x1borg.apache.drill.exec.protoB\x12\x43oordinationProtosH\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DRILLBITENDPOINT = _descriptor.Descriptor(
  name='DrillbitEndpoint',
  full_name='exec.DrillbitEndpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='exec.DrillbitEndpoint.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_port', full_name='exec.DrillbitEndpoint.user_port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='control_port', full_name='exec.DrillbitEndpoint.control_port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_port', full_name='exec.DrillbitEndpoint.data_port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roles', full_name='exec.DrillbitEndpoint.roles', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=151,
)


_DRILLSERVICEINSTANCE = _descriptor.Descriptor(
  name='DrillServiceInstance',
  full_name='exec.DrillServiceInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='exec.DrillServiceInstance.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='registrationTimeUTC', full_name='exec.DrillServiceInstance.registrationTimeUTC', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='exec.DrillServiceInstance.endpoint', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=258,
)


_ROLES = _descriptor.Descriptor(
  name='Roles',
  full_name='exec.Roles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sql_query', full_name='exec.Roles.sql_query', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logical_plan', full_name='exec.Roles.logical_plan', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='physical_plan', full_name='exec.Roles.physical_plan', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='java_executor', full_name='exec.Roles.java_executor', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distributed_cache', full_name='exec.Roles.distributed_cache', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=412,
)

_DRILLBITENDPOINT.fields_by_name['roles'].message_type = _ROLES
_DRILLSERVICEINSTANCE.fields_by_name['endpoint'].message_type = _DRILLBITENDPOINT
DESCRIPTOR.message_types_by_name['DrillbitEndpoint'] = _DRILLBITENDPOINT
DESCRIPTOR.message_types_by_name['DrillServiceInstance'] = _DRILLSERVICEINSTANCE
DESCRIPTOR.message_types_by_name['Roles'] = _ROLES

DrillbitEndpoint = _reflection.GeneratedProtocolMessageType('DrillbitEndpoint', (_message.Message,), dict(
  DESCRIPTOR = _DRILLBITENDPOINT,
  __module__ = 'Coordination_pb2'
  # @@protoc_insertion_point(class_scope:exec.DrillbitEndpoint)
  ))
_sym_db.RegisterMessage(DrillbitEndpoint)

DrillServiceInstance = _reflection.GeneratedProtocolMessageType('DrillServiceInstance', (_message.Message,), dict(
  DESCRIPTOR = _DRILLSERVICEINSTANCE,
  __module__ = 'Coordination_pb2'
  # @@protoc_insertion_point(class_scope:exec.DrillServiceInstance)
  ))
_sym_db.RegisterMessage(DrillServiceInstance)

Roles = _reflection.GeneratedProtocolMessageType('Roles', (_message.Message,), dict(
  DESCRIPTOR = _ROLES,
  __module__ = 'Coordination_pb2'
  # @@protoc_insertion_point(class_scope:exec.Roles)
  ))
_sym_db.RegisterMessage(Roles)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033org.apache.drill.exec.protoB\022CoordinationProtosH\001'))
# @@protoc_insertion_point(module_scope)
